export type Role = "admin" | "sales" | "finance";
export type Profile = {
  id: string;
  name: string;
  role: Role;
  active: boolean;
  version: number;
};
export type Product = {
  id: string;
  sku: string;
  name: string;
  category: string;
  unit: string;
  purchase_price: string | null;
  brand?: string;
  variant?: string;
  list_price?: string | null;
  list_price_tax_included?: boolean;
  list_price_as_of?: string | null;
  list_price_source?: string;
  pack_quantity?: number | null;
  archived: boolean;
  version: number;
};
export type Customer = {
  id: string;
  owner_id: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  archived: boolean;
  version: number;
};
export type Settings = {
  company_name: string;
  address: string;
  contact: string;
  logo_path: string | null;
  tax_percent: string;
  profit_percent: string;
  marketing_percent: string;
  operational_percent: string;
  tax_enabled?: boolean;
  tax_name?: string;
  tax_mode?: "added" | "included";
  tax_base?: "products" | "products_shipping";
  invoice_prefix: string;
  version: number;
};
export type LineInput = {
  client_line_id?: string;
  product_id: string;
  quantity: string;
  profit_percent: string;
  marketing_percent: string;
  operational_percent: string;
  rounding: string;
  selected_price: string | null;
};
export type DraftInput = {
  customer_id: string;
  shipping?: string | null;
  shipping_address?: string;
  shipping_carrier?: string;
  tax?: {
    enabled: boolean;
    name: string;
    rate: string;
    mode: "added" | "included";
    base: "products" | "products_shipping";
  };
  operations?: { name: string; percent: string }[];
  target_percent?: string;
  marketing_percent?: string;
  invoice_date?: string;
  due_date: string;
  notes: string;
  lines: LineInput[];
};
export type CalculatedLine = {
  line_id: string;
  product_id: string;
  product_version: number;
  sku: string;
  name: string;
  brand?: string;
  variant?: string;
  unit: string;
  quantity: string;
  purchase_price: string;
  shipping_per_unit: string;
  profit_percent: string;
  marketing_percent: string;
  operational_percent: string;
  recommended_price: string;
  selected_price: string;
  line_total: string;
  operational_cost: string;
  marketing_cost: string;
  profit: string;
};
export type Calculation = {
  company: Settings;
  customer: Customer;
  lines: CalculatedLine[];
  shipping: string;
  provisional?: boolean;
  displayed_subtotal?: string;
  product_revenue?: string;
  subtotal: string;
  purchase: string;
  operational: string;
  marketing: string;
  tax_percent: string;
  tax_name?: string;
  tax_enabled?: boolean;
  tax_mode?: "added" | "included";
  tax_product?: string;
  tax_shipping?: string;
  tax_base?: string;
  tax: string;
  total: string;
  profit: string;
  operational_items?: { name: string; percent: string; amount: string }[];
  cost_base?: string;
  target_profit?: string;
  profit_percent?: string;
  target_gap?: string;
  profit_status?: "target" | "below" | "even" | "loss";
  total_cost?: string;
  notes: string;
  due_date: string;
  invoice_date?: string;
  shipping_rule: string;
  shipping_address?: string;
  shipping_carrier?: string;
};
export type Preview = {
  calculation: Calculation;
  hash: string;
  version: number;
};
export type Draft = {
  id: string;
  owner_id: string;
  inputs: DraftInput;
  calculation: Calculation;
  calculation_hash: string;
  version: number;
  revision_of: string | null;
  updated_at: string;
};
export type Invoice = {
  id: string;
  draft_id: string;
  owner_id: string;
  number: string;
  snapshot: Calculation;
  total: string;
  paid: string;
  version: number;
  revision_of: string | null;
  issued_at: string;
  cancelled_at: string | null;
  cancellation_reason: string | null;
};
export type Payment = {
  id: string;
  invoice_id: string;
  amount: string;
  paid_on: string;
  method: string;
  reference: string;
  version: number;
  cancelled_at: string | null;
  cancellation_reason: string | null;
  created_at: string;
};
export type Category = {
  id: string;
  name: string;
  archived: boolean;
  version: number;
};
export type Audit = {
  id: number;
  actor_id: string;
  action: string;
  entity: string;
  record_id: string;
  details: Record<string, unknown>;
  created_at: string;
};
export type Dashboard = {
  sales: string;
  payments: string;
  outstanding: string;
  invoice_count: number;
  recent_invoices: Invoice[];
  recent_payments: Payment[];
};
